### ISSUE TITLE
Amend Rakudoc to use new features

### ISSUE THREAD

**Issue by finanalyst** [Raku/RakuDoc-GAMMA#50]
@thoughtstream @lizmat @zag 
I have finally got my [RakuAST-RakuDoc-Render](https://github.com/finanalyst/rakuast-rakudoc-render) working.
It can now render both the [renderer consistency file - rakudociem-ipsum.rakudoc](https://finanalyst.github.io/samples_rakudociem-ipsum) and the [RakuDoc specification source](https://finanalyst.github.io/samples_rakudoc).

Some of the examples of the RakuDoc specification were written in an ad hoc manner because the features had not been fully implemented (eg. numbered headings and items).

The RakuDoc-GAMMA file needs amending to use RakuDoc directly.

In addition, some extra eyes on the renderings above would be appreciated.
Known flaws (CSS and styling mainly):
- Some Intra-table lines are not properly rendered 
- There is redundant white space in `text` type styling. [fixed]

**Comment by zag** [comment]
that's cool news about the RakuAST-RakuDoc-Render progress!
 i'm quite tied up with other tasks at the moment, but it's great to see this moving forward.
 thanks for keeping in the loop!

**Comment by finanalyst** [comment]
@zag I saw your podlite web work. It's looking good too.

**Comment by thoughtstream** [comment]
Outstanding work, @finanalyst!

Just a few points (for a sufficiently large value of _“few”_):

1. The code block immediately after: _The general syntax of `=place` is_
  should have an `:allow<R>` (so that the `R<URL>` etc. are rendered as replaceables)

2. In the code block immediately after: _For example, to specify a para block in delimited form:_
  there are two highlighting errors. On the first line the `:meta<data>` is highlighted oddly,
  as :met**a\<data\>** (seemingly mistaking the `a<data>` for a formatting code). This also 
  occurs on the first code block of the subsequent section **extended form. See also
  `y<firstvalue>`, `w< B C I >`, `n<Experimental data>`, _etc._ later in the rendering.

3. Secondly, on the final line of the same code block, the `=end para` is not highlighted
  (I would have expected it to be).

3. In the code block of the section **Abbreviated form**, the trailing non-para text is
  highlighted oddly. Random words are highlighted in cyan, or blue.

4. In the section **Aliases**, immediately after: _This would produce:_
  The rendering of the disclaimer and the three bullet points seems...infelicitous.
  Though this might be a bug in the original source, not in the rendering.

6. In the section **Aliases**, the final code block does not seem to be rendered correctly.
  (Lots of unclosed `A<B`, which doesn’t seem right).

7. Throughout the document: many (maybe most) of the rendered code blocks
  seem to be visually outdenting their first lines. For example:
```
    sub MAIN(
            Str $first,    #= the first CLI parameter
            Int :$verbose, #= an integer to indicate output, 0 = no output
        )


    =begin data :key<Virtues>
        Laziness
        Impatience
        Hubris
        =end data

        say 'The three virtues are:';
        say $=data<Virtues>;
```

8. For some rendered examples, the relative indenting of text and bullet lists seems wrong.
  For example:
```
        The three suspects are:

    . Happy
    . Sleepy
    . Grumpy
```

9. In the section **Multi-paragraph lists**, the highlighting is mistaking the apostrophe
  in `Let's` for the start of a Raku string, which produces very odd highlighting.

10. In the section **Numbered definitions**, I would argue that the autogenerated numbers
   on the definitions ought to be rendered the same as the definition text (i.e. bold)

11. In the section **Formulae**, immediately after: _...may either be rendered “accurately”:_
   The formulae are not in fact rendered accurately (or at all!)

12. In the section **Formatting codes**, in the first table, the Instruction and HTML columns
   shouldn’t be actually rendered (they should show the raw RakuDoc and HTML equivalents).
   This is both a bug in the original file (see below) and an error in rendering
   (the renderer should escape the literal `<` and `>` in the plaintext HTML examples
   so that their meanings don’t leak through into the HTML rendering).
   As for the original RakuDoc source, the table:

        Inline markup   Instruction   Mnemonic              HTML equivalent     Markdown equivalent
        =============   ===========   ===================   ===============     ===================
        Basis           B<text>       "B for Basis"         <b>text</b>         **text**
        Important       I<text>       "I for Important"     <i>text</i>         *text*
        Unusual         U<text>       "U for Unusual"       <u>text</u>         __text__
        Strikethrough   O<text>       "O for Overstrike"    <s>text</s>         ~~text~~
        Superscript     H<text>       "H for High text"     <sup>text</sup>     ^text^
        Subscript       J<text>       "J for Junior text"   <sub>text</sub>     ~text~
        Code            C<text>       "C for Code"          <code>text</code>   `text`

   should be something like:

        Inline markup   Instruction   Mnemonic              HTML equivalent       Markdown equivalent
        =============   ===========   ===================   ===============       ===================
        Basis           C«B<text>»    "B for Basis"         C«<b>text</b>»        C«**text**»
        Important       C«I<text>»    "I for Important"     C«<i>text</i>»        C«*text*»
        Unusual         C«U<text>»    "U for Unusual"       C«<u>text</u>»        C«__text__»
        Strikethrough   C«O<text>»    "O for Overstrike"    C«<s>text</s>»        C«~~text~~»
        Superscript     C«H<text>»    "H for High text"     C«<sup>text</sup>»    C«^text^»
        Subscript       C«J<text>»    "J for Junior text"   C«<sub>text</sub>»    C«~text~»
        Code            C«C<text>»    "C for Code"          C«<code>text</code>   C«`text`»

13. In the section **Links**, the first two indented `L<...>` examples are RakuDoc code blocks
   and should be rendered literally, (_e.g._ `L< dealing with the filesystem | type/IO.Path.* >`),
   not converted to HTML `<a>` constructs (_e.g._ `<a href="type/IO.Path.txt"> dealing with the filesystem </a>`)

14. In the section **Space-preserving text**, the first code block is being misrendered,
   and loses the all-important newline after the `S<`, which makes the example wrong.
   Also the highlighting of the (incorrect) `S<dot` is weird.

15. In the section **Unicode and HTML references**, the rendering of the final code block
   is not rendering the alternate display texts in the examples, making the examples
   unfathomably miraculuous. :-)

16. In the section **Indexing terms**, the third and fourth code blocks are misrendered
   (possibly due to the use of `:allow`ed `B<>` markup within them).


That’s quite a bit of nit-picking, I know, but it doesn’t detract from the overall achievement,
which is extremely impressive. Especially, the table-handling, which is awesome!

**Comment by finanalyst** [comment]
@thoughtstream Thank you for the attention to detail.
I noticed a number of the problems and addressed some of them. The indenting was/is problematic. But I think I have solved most of them. There were also some problems with the RakuDoc source itself that only came to light when I began rendering the source as opposed to the workarounds we used to illustrate the code.

Please have a look at the newest version of the rendered RakuDoc text.
(I'll handle your comment on R<> for the next rendering)

The highlighting of metaoptions on RakuDoc blocks is a known flaw of the Rainbow highlighter and an issue has been raised. @patrickbkr has said he will deal with it in due course. I'll also have a go in due course.

It should be born in mind that the Raku highlighters (Patrick's Rainbow and Liz's deparse-highlighter) are the first ones that differentiate categories in RakuDoc, so kudos to them. In addition, most of the snippets in this source illustrate RakuDoc. All the other Raku documentation sources (some 700 files) illustrate Raku. Hence the priority is to get the Raku syntax right. 

I have noticed some oddly rendered snippets for RakuDoc rendering, eg the example in the section on multi-paragraph lists. I'll look at this to see whether it is a Rainbow question or a RakuDoc source.

I think this may take a few iterations to get right.

**Comment by patrickbkr** [comment]
> The highlighting of metaoptions on RakuDoc blocks is a known flaw of the Rainbow highlighter and an issue has been raised. @patrickbkr has said he will deal with it in due course. I'll also have a go in due course.

I think I'll need some more guidance on this to understand what the desired outcome is.

Given there is some `=code` block with an `:allow(B)`. Should the highlighter generate Raku code tokens as usual and sprinkle RakuDoc tokens in between? I'd say that's the right thing to do when highlighting the RakuDoc file itself.

How is a pipeline to render some RakuDoc file meant to handle this? At one point it'll need to convert that block of Raku code to a marked up form. Will it first treat the content as plain text, find and remove the RakuDoc markup, pass the result to Rainbow and apply the removed RakuDoc markup afterwards? Will it pass the content unchanged to Rainbow and somehow try to make sense of the RakuDoc tokens the resulting token list contains?

> [update 2] I think this needs to be handled by the renderer, not the highlighter. The highlighter does not 'know' whether a snippet is Raku or RakuDoc, but the renderer does. So, I will filter out string delimiter and string tokens and treat them as text in a RakuDoc snippet. [update 3] The above will not work because the tokeniser is ignoring the inner structure of the string

Unsure this will help, but are you aware, that you can use Rainbow to parse strings/RakuDoc/comments/Regexes directly? There are grammar rules for each of them. They are always listed below a comment `# Starters -----` in [here](https://git.sr.ht/~patrickb/Rainbow/tree/main/item/lib/Rainbow/RakuGrammar.rakumod). You'll need to write a custom `tokenize()` function calling the respective rule. If this is in any way interesting, ping me, I can help get you started.

**Comment by finanalyst** [comment]
@patrickbkr I've found raising an issue on sourcehut quite difficult to navigate, so I'll respond here.
- Please take a look at [the RakuDoc specification as rendered](https://finanalyst.github.io/samples_rakudoc) which shows quite a representative variety of RakuDoc.
- The metadata options are described in more detail in the [RakuDoc specification at metadata syntax](https://finanalyst.github.io/samples_rakudoc#Metadata%20syntax). 
- in brief:
  1. options can only appear after `=begin <blockname>` or `=for <blockname>` and cannot appear after just `=<blockname>` where **<blockname>** is something like *head* or *code*
  2. options are very similar in syntax to Raku pairs.
  3. the content of an option can only be Raku, it cannot contain embedded RakuDoc.
  
I was not aware that I could parse a RakuDoc string directly. That would be great. Please let me know how to start.

**Comment by finanalyst** [comment]
@thoughtstream I now have had the chance to go through your flaws. 
Appologies for responding without looking carefully. You have discovered a number of distinct errors. 
I think I have fixed 1,7, and 14

Here is a more careful analysis. Numbered as you did
1. Error in GAMMA source - fixed
2. `:meta<xxx>` is highlighted as `:met` `A<xxx>`. A Rainbow issue that is now being addressed. The Grammar does not recognised any "config" elements. 
3. `=end` highlighting is flawed. I hope to fix this with a new RakuDoc tokeniser (as suggested by @patrickbkr )
4. Ambient text is being treated as Raku so various keywords are being highlighted as subs etc. This will be addressed by creating a separate RakuDoc tokeniser (as above).
5. More analysis is needed. It could be a renderer error. Embedded `=item` in `=alias` was not implemented before. 
6.  As 5.
7. This was the indenting problem I mentioned. I think I have solved it. 
8. List indenting - Meh! Fix one indent, get another for free! Needs more investigation
9. Mentioned already. Will fix with RakuDoc tokeniser
10. Numbered definitions. The numeration should be the same as the definition. So there's a bug. Needs fixing
11. This is an instance where the the GAMMA source needs updating. `=formula` and `F<>` are implemented as can be seen from [rakudociem-ipsum](https://finanalyst.github.io/samples_rakudociem-ipsum#Fabulous%20identity)
12. Format table. Stripping out the markup was my error - will fix.
13. Really odd. Needs investigation
14. S<> markup seems to have been fixed.
15. Unicode with `|` seems to be something missed from the renderer.
16. Indexing items. This is a render error in that the meta part is treated as an ordinary string.

**Comment by thoughtstream** [comment]
@finanalyst, that's already looking much better.
(And I didn't detect any newly introduced bugs either :-)

Great work by you and @patrickbkr!

**Comment by finanalyst** [comment]
@thoughtstream I have worked through all of the errors you found. 
Several were deeper than I expected. One led to a change in the specification.

There are now two remaining issues:
- a syntax highlighting issue being resolved with @patrickbkr (it is only in RakuDoc blocks, where the options/configuration extends more than one line)
- Embedding B markup within other markup within a `=for code :lang<RakuDoc>` is an issue being resolved by @lizmat and the rendering currently is naive.

@thoughtstream Would it be possible for you to review the newly rendered version again to see whether those are the only problems?

**Comment by thoughtstream** [comment]
@finanalyst, I will review the latest rendered version as soon as I have time.
At this stage that will probably be early next week.

**Comment by thoughtstream** [comment]
@finanalyst, I have now looked through your most recent render of the spec document...which looks great. 
Apart from the two remaining issues you already noted, the only issues I still have are:

1. It’s not a rendering issue _per se_, but I think the default style for `D<>` 
   definition markups should be ***bold italic***, not just **bold**.
   I’d be inclined to use ***bold italic*** for `=defn` definitions as well,
   both for consistency and to help distinguish them from headings.
   Moreover, later in the specification we explicitly suggest that:

   > The definition term in a `D<>` is rendered distinctly (typically in ***bold italics***)

1. In the section [***Markup instruction syntax***](https://finanalyst.github.io/samples/rakudoc#Markup%20instruction%20syntax), the first lines
   of each `=begin item` block are not rendering at all,
   making the associated information incomprehensible.

1. In [the ***Raku’s mascot*** example](https://finanalyst.github.io/samples/rakudoc#Raku's%20mascot), the caption is being rendering beside
   the image, rather than below it. Is that intentional?
   (Captions are traditionally rendered ***under*** the items they caption.)

1. In [the section on ***Formulae***](https://finanalyst.github.io/samples/rakudoc#Formulae),  the `F< FORMULA >` 
   (_i.e._ the `C«F< FORMULA >»` in the source document)
   between the _“either”_ and the _“or”_ is not being rendered in the sentence:
   > That is, the `=formula` block accepts an `:alt` metaoption, and the syntax for the `F<>` instruction is either or `F< ALT | FORMULA >`.
   

1. Near the end of [the section on ***Formatting codes***](https://finanalyst.github.io/samples/rakudoc#Formatting%20codes), 
   the example after _“...This can be achieved with:”_ is not being rendered.
   However, I’m pretty sure that is just an error in the source document.
   Specifically, [the source line that’s not being rendered](https://github.com/Raku/RakuDoc-GAMMA/blob/8a915a5f5cbacc8fe9f49646ebcb927cb282561c/rakudoc_draft_3.rakudoc#L3118):
   ```rakudoc
        =config C :allow<B>
   ```
   ...is (correctly) acting as an actual `=config`, not as an implicit code block. It should be:
   ```rakudoc
        =begin code
        =config C :allow<B>
        =end code
   ```

1. In the section on ***Links***, the `=config C :allow<R>` is not being honoured,
   causing the second sentence to be rendered:

   &nbsp;&nbsp;&nbsp;&nbsp;The general syntax is `L< R<LABEL> | R<TARGET> >`

   ...instead of:

   &nbsp;&nbsp;&nbsp;&nbsp;The general syntax is <code>L&lt; <em><strong>LABEL</strong></em> | <em><strong>TARGET</strong></em> &gt;</code>


Also, while reading through this now-beautifully-formatted spec I did notice a few bugs
in the source document itself, as follows:

1. In the [the example for `=place`](https://github.com/Raku/RakuDoc-GAMMA/blob/8a915a5f5cbacc8fe9f49646ebcb927cb282561c/rakudoc_draft_3.rakudoc#L241C1-L244C10), the final line of the example should be
   offset three characters to compensate for the extra `R<>`
   in the previous line and to allow the two option descriptions
   to line up neatly. Also, the final line should be capitalized. Hence:
   ```rakudoc
    =begin code :lang<RakuDoc> :allow<R>
        =place R<URL> R<OPTIONS>
        =           R<MORE OPTIONS IF NECESSARY>
    =end code
   ```

1. The indented code example at [line 409 of the source](https://github.com/Raku/RakuDoc-GAMMA/blob/8a915a5f5cbacc8fe9f49646ebcb927cb282561c/rakudoc_draft_3.rakudoc#L409)
   needs a blank line above it to stop it being consumed
   as part of the preceding paragraph. That is:
   ```rakudoc
    A renderer may provide a mechanism for allowing RakuDoc within a metadata option
    but the value part must still conform to Raku semantics, for example,

        :caption('This is a heading with I<important markup> in it')
   ```

1. There’s an _“is”_ missing at [line 596 of the source](https://github.com/Raku/RakuDoc-GAMMA/blob/8a915a5f5cbacc8fe9f49646ebcb927cb282561c/rakudoc_draft_3.rakudoc#L596). The sentence should be:
  _The general principle is that more block-specific configurations of metadata take precedence over_

1. In the section ***Summary***, in the table for ***Blocks***,
   [the first row](https://github.com/Raku/RakuDoc-GAMMA/blob/8a915a5f5cbacc8fe9f49646ebcb927cb282561c/rakudoc_draft_3.rakudoc#L3844) is missing a `:header` metaoption.

1. In the section ***Summary***, in the table for ***Markup instructions***,
   [the first row](https://github.com/Raku/RakuDoc-GAMMA/blob/8a915a5f5cbacc8fe9f49646ebcb927cb282561c/rakudoc_draft_3.rakudoc#L3844) is also missing a `:header` metaoption.


Otherwise, everything looks terrific. Rendering (almost) everything so well
is a towering achievement, of which you should be immensely proud.

**Comment by finanalyst** [comment]
@thoughtstream Thank you for the compliment. In case you are not aware, I contributed two Advent articles about RakuDoc and the new specification. I hope to get a third one with a container that can be included in github actions so that all `docs/` files in RakuDoc are rendered to `*.md` in the repo root upon push.

I'll go through the above in detail after that. Error 5 may be linked to a parsing issue, where `=for` and `=begin` yield different AST when there is an internal directive.

**Comment by finanalyst** [comment]
@thoughtstream
I ran into a problem with item 2. @lizmat helped me solve it - I was about to give up.

Changes to match @thoughtstream latest review points
1. D<> rendering. - changed css
2. `B< <Instruction> >` - This is an HTML escaping problem because `<Instruction>` needs escaping. Problem was with embedded variants, eg `B<I< <ins> > >`
3. Image caption. - sorted with extra div and flex column css
4. Formula issue - this is actually a RakuDoc source error `C«<F< FOR` should be `C«F< FOR`.  Fixed in source
5. Indented config - This parallels a problem with `=config` as reported in [Rakudo #5723](https://github.com/rakudo/rakudo/issues/5723#issue-2724060918)

to be continued

**Comment by finanalyst** [comment]
@thoughtstream I think this issue is completed.

**Comment by thoughtstream** [comment]
> @thoughtstream I think this issue is completed.

I concur. Excellent work by both @finanalyst and @lizmat!

One very minor point: the fix for item 4 introduced a minor error.
It now reads:

> That is, the `=formula` block accepts an \`:alt\` metaoption,

In other words, the <code>\`:alt\`</code> in the source should be a `C<:alt>`.

**Comment by finanalyst** [comment]
@thoughtstream thank you for reviewing again. I wanted to ask, but ... . I'll fix the specification.

**Comment by finanalyst** [comment]
@thoughtstream FWIW I have completed work on a container file with the generic renderer, two HTML renderers, and a MarkDown renderer. The docker container can be used with a github CI to render `docs/` rakudoc sources into a repo root (eg README.rakudoc) so theres no need to write in MarkDown. An advent article will be coming out soon about my journey to a CI integration.

Now I am giving the MarkDown renderer some TLS to fix the flaws you found in the HTML.

The next task for me is to develop some custom RakuDoc blocks to create the HTML that is included in a navigation bar. The idea is that a multi lingual web site should have a separation between the language of the UI and the language of the content. Currently, all (AFAIK) content management systems can switch from pages in one language to pages in another, but as someone who can speak read and write in three languages (English, Russian and Welsh), I dont want to learn the UI setup for each language separately when switching between content. 

Any way that is in the [elucid8](https://github.com/elucid8) project.
